### ISSUE TITLE
🛕 Finalize the apply & review email templates

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-api#42]
**Type**: api

**FOF**: 2

## Description
- Update the contents of the emails that ClearPath sends out when an application is sent/reviewed
- We can modify both the header and body of an email
  - It would also be cool to shorten our sender email address
  - Currently it's `clearpathnyc=gmail.com@mail.clearpathnyc.com` 🤢  

## Screenshot
Current Apply Email:
<img width="870" alt="image" src="https://github.com/ClearPathNYC/clearpath-api/assets/45826922/0c7c86a3-7293-4168-9fef-ef2ad00bd3a1">

Current Review Email:
<img width="870" alt="image" src="https://github.com/ClearPathNYC/clearpath-api/assets/45826922/f964463c-941b-41b1-ae9f-ce7e1285df5b">

## Where's the code?
- File: https://github.com/ClearPathNYC/clearpath-api/blob/dev/server/services/email/index.ts
  - Apply Email: `sendAppliedEmail`
  - Review Email: `sendApplicationReviewedEmail`
- We might need to update the arguments to these functions to pass extra info  

## Todo
- [ ] Update the apply email
- [ ] Update the review email
- [ ] Test sending out emails by running `yarn dev` on the backend

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

## Learnings
- Upon successful completion of this issue you are ready for a strong career in Human Resources 💼
